hake/Config.hs.template: switch optimization level back to -O2
-O3 enables loop unrolling which causes problems with thc, due to loops with
inline assembly being unrolled.

For example:
../usr/tests/thctest/thctest.c: Assembler messages:
../usr/tests/thctest/thctest.c:53: Error: symbol `_thc_cont_return_5' is already defined
../usr/tests/thctest/thctest.c:69: Error: symbol `_thc_cont_return_6' is already defined
../usr/tests/thctest/thctest.c:91: Error: symbol `_thc_cont_return_7' is already defined
../usr/tests/thctest/thctest.c:111: Error: symbol `_thc_cont_return_8' is already defined